export * from "./check-is-domain-disposable"
export {default as checkIsDomainDisposable} from "./check-is-domain-disposable"
export * from "./get-server-settings"
export {default as getServerSettings} from "./get-server-settings"
export * from "./signup"
export {default as signup} from "./signup"
export * from "./verify-email"
export {default as verifyEmail} from "./verify-email"
export * from "./resend-email-verification-code"
export {default as resendEmailVerificationCode} from "./resend-email-verification-code"
export * from "./refresh-token"
export {default as refreshToken} from "./refresh-token"
export * from "./logout"
export {default as logout} from "./logout"
export * from "./get-aliases"
export {default as getAliases} from "./get-aliases"
export * from "./create-alias"
export {default as createAlias} from "./create-alias"
export * from "./update-account"
export {default as updateAccount} from "./update-account"
export * from "./login-with-email"
export {default as loginWithEmail} from "./login-with-email"
export * from "./verify-login-with-email"
export {default as verifyLoginWithEmail} from "./verify-login-with-email"
export * from "./resend-email-login-code"
export {default as resendEmailLoginCode} from "./resend-email-login-code"
export * from "./update-preferences"
export {default as updatePreferences} from "./update-preferences"
export * from "./get-reports"
export {default as getReports} from "./get-reports"
export * from "./get-report"
export {default as getReport} from "./get-report"
export * from "./get-alias"
export {default as getAlias} from "./get-alias"
export * from "./update-alias"
export {default as updateAlias} from "./update-alias"
